### ISSUE TITLE
First version

### ISSUE THREAD

**Issue by nWacky** [comcava/open_squeezer#2]
- [x] Find and show blurry photos (#1)
- [x] Allow deleting blurry photos (#3)
- [x] Scan photos in multiple threads (#3)
- [x] Show large video files (#4)
- [ ] Consider using HaarWavelett Transform for blur detection
